application: your-app-id
version: 1
runtime: go111

handlers:

- url: /caterpillar/static/mng/
  static_files: caterpillar/static/mng/index.html
  upload: caterpillar/static/mng/index.html
  login: admin

- url: /caterpillar/static/(.*)
  static_files: caterpillar/static/\1
  upload: caterpillar/static/.*
  login: admin

- url: /caterpillar/api/.*
  script: auto
  login: admin

- url: /_ah/queue/go/delay
  script: auto
  login: admin

- url: /caterpillar/.*
  script: auto

- url: /.*\.view
  script: auto

- url: /.*\.edit
  script: auto
  login: admin

- url: /.*
  script: auto


